### ISSUE TITLE
Install bundler as part of the setup

### ISSUE THREAD

**Issue by Momoumar** [Flatbook/laptop#19]
The script should install [bundler](https://bundler.io/) as it is referred on [Flatbook](https://github.com/Flatbook/flatbook) setup.

**Comment by IliasDeros** [comment]
@Momoumar It is installed as part of the flatbook setup

```
system_or_throw "rbenv global $(cat .ruby-version) && gem install bundler; bundle install"
```

**Source**
https://github.com/Flatbook/flatbook/blob/master/bin/setup#L48

**Comment by IliasDeros** [comment]
I think it's better to keep it in the flatbook, to ensure we always have bundler installed for flatbook's ruby version. Closing issue ✅
